name: Telegram Bot Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes to ensure bot stays active

permissions:
  contents: read

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 25  # Set timeout to slightly less than the cron interval
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the bot
      run: |
        # Set a timeout to gracefully exit before GitHub's job timeout
        timeout 23m python main.py
      shell: bash
